### ISSUE TITLE
composer require throws exception

### ISSUE THREAD

**Issue by mprokopov** [OXIDprojects/passwordpolicy#2]
The `composer require oxid-professional-services/password-policy` command throws the exception as on the screenshot

![Screen Shot 2021-01-15 at 16 04 51](https://user-images.githubusercontent.com/549392/104742970-6a267100-574b-11eb-9a9d-4fd8362db6b6.png)

oxid eshop v6.2.2

**Comment by BernhardScheffold** [comment]
This is fixed with version 0.8.6
